/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as landingTrialRouteImport } from './routes/(landing)/trial'
import { Route as landingSupportRouteImport } from './routes/(landing)/support'
import { Route as landingPrivacyRouteImport } from './routes/(landing)/privacy'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedStaffsIndexRouteImport } from './routes/_authenticated/staffs/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSaleOrdersIndexRouteImport } from './routes/_authenticated/sale-orders/index'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedDataMigrationIndexRouteImport } from './routes/_authenticated/data-migration/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedBankAccountsIndexRouteImport } from './routes/_authenticated/bank-accounts/index'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './routes/_authenticated/suppliers/$supplierId'
import { Route as AuthenticatedSupplierPaymentsHistoryRouteImport } from './routes/_authenticated/supplier-payments/history'
import { Route as AuthenticatedStaffsStaffIdRouteImport } from './routes/_authenticated/staffs/$staffId'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSaleOrdersHistoryRouteImport } from './routes/_authenticated/sale-orders/history'
import { Route as AuthenticatedSaleOrdersDetailRouteImport } from './routes/_authenticated/sale-orders/detail'
import { Route as AuthenticatedPurchaseOrdersHistoryRouteImport } from './routes/_authenticated/purchase-orders/history'
import { Route as AuthenticatedPurchaseOrdersDetailRouteImport } from './routes/_authenticated/purchase-orders/detail'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedInventoryAdjustmentsIndexRouteImport } from './routes/_authenticated/inventory/adjustments/index'
import { Route as AuthenticatedInventoryAdjustmentsNewRouteImport } from './routes/_authenticated/inventory/adjustments/new'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const landingTrialRoute = landingTrialRouteImport.update({
  id: '/(landing)/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const landingSupportRoute = landingSupportRouteImport.update({
  id: '/(landing)/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPrivacyRoute = landingPrivacyRouteImport.update({
  id: '/(landing)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffsIndexRoute =
  AuthenticatedStaffsIndexRouteImport.update({
    id: '/staffs/',
    path: '/staffs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSaleOrdersIndexRoute =
  AuthenticatedSaleOrdersIndexRouteImport.update({
    id: '/sale-orders/',
    path: '/sale-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataMigrationIndexRoute =
  AuthenticatedDataMigrationIndexRouteImport.update({
    id: '/data-migration/',
    path: '/data-migration/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankAccountsIndexRoute =
  AuthenticatedBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplierPaymentsHistoryRoute =
  AuthenticatedSupplierPaymentsHistoryRouteImport.update({
    id: '/supplier-payments/history',
    path: '/supplier-payments/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffsStaffIdRoute =
  AuthenticatedStaffsStaffIdRouteImport.update({
    id: '/staffs/$staffId',
    path: '/staffs/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSaleOrdersHistoryRoute =
  AuthenticatedSaleOrdersHistoryRouteImport.update({
    id: '/sale-orders/history',
    path: '/sale-orders/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaleOrdersDetailRoute =
  AuthenticatedSaleOrdersDetailRouteImport.update({
    id: '/sale-orders/detail',
    path: '/sale-orders/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersHistoryRoute =
  AuthenticatedPurchaseOrdersHistoryRouteImport.update({
    id: '/purchase-orders/history',
    path: '/purchase-orders/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersDetailRoute =
  AuthenticatedPurchaseOrdersDetailRouteImport.update({
    id: '/purchase-orders/detail',
    path: '/purchase-orders/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryAdjustmentsIndexRoute =
  AuthenticatedInventoryAdjustmentsIndexRouteImport.update({
    id: '/inventory/adjustments/',
    path: '/inventory/adjustments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryAdjustmentsNewRoute =
  AuthenticatedInventoryAdjustmentsNewRouteImport.update({
    id: '/inventory/adjustments/new',
    path: '/inventory/adjustments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/privacy': typeof landingPrivacyRoute
  '/support': typeof landingSupportRoute
  '/trial': typeof landingTrialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/purchase-orders/detail': typeof AuthenticatedPurchaseOrdersDetailRoute
  '/purchase-orders/history': typeof AuthenticatedPurchaseOrdersHistoryRoute
  '/sale-orders/detail': typeof AuthenticatedSaleOrdersDetailRoute
  '/sale-orders/history': typeof AuthenticatedSaleOrdersHistoryRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/staffs/$staffId': typeof AuthenticatedStaffsStaffIdRoute
  '/supplier-payments/history': typeof AuthenticatedSupplierPaymentsHistoryRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/bank-accounts/': typeof AuthenticatedBankAccountsIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/data-migration/': typeof AuthenticatedDataMigrationIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/sale-orders/': typeof AuthenticatedSaleOrdersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/staffs/': typeof AuthenticatedStaffsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/inventory/adjustments/new': typeof AuthenticatedInventoryAdjustmentsNewRoute
  '/inventory/adjustments/': typeof AuthenticatedInventoryAdjustmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/privacy': typeof landingPrivacyRoute
  '/support': typeof landingSupportRoute
  '/trial': typeof landingTrialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/purchase-orders/detail': typeof AuthenticatedPurchaseOrdersDetailRoute
  '/purchase-orders/history': typeof AuthenticatedPurchaseOrdersHistoryRoute
  '/sale-orders/detail': typeof AuthenticatedSaleOrdersDetailRoute
  '/sale-orders/history': typeof AuthenticatedSaleOrdersHistoryRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/staffs/$staffId': typeof AuthenticatedStaffsStaffIdRoute
  '/supplier-payments/history': typeof AuthenticatedSupplierPaymentsHistoryRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/bank-accounts': typeof AuthenticatedBankAccountsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/data-migration': typeof AuthenticatedDataMigrationIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/sale-orders': typeof AuthenticatedSaleOrdersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staffs': typeof AuthenticatedStaffsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/inventory/adjustments/new': typeof AuthenticatedInventoryAdjustmentsNewRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(landing)/privacy': typeof landingPrivacyRoute
  '/(landing)/support': typeof landingSupportRoute
  '/(landing)/trial': typeof landingTrialRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/purchase-orders/detail': typeof AuthenticatedPurchaseOrdersDetailRoute
  '/_authenticated/purchase-orders/history': typeof AuthenticatedPurchaseOrdersHistoryRoute
  '/_authenticated/sale-orders/detail': typeof AuthenticatedSaleOrdersDetailRoute
  '/_authenticated/sale-orders/history': typeof AuthenticatedSaleOrdersHistoryRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/staffs/$staffId': typeof AuthenticatedStaffsStaffIdRoute
  '/_authenticated/supplier-payments/history': typeof AuthenticatedSupplierPaymentsHistoryRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/_authenticated/bank-accounts/': typeof AuthenticatedBankAccountsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/data-migration/': typeof AuthenticatedDataMigrationIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/sale-orders/': typeof AuthenticatedSaleOrdersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/staffs/': typeof AuthenticatedStaffsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/inventory/adjustments/new': typeof AuthenticatedInventoryAdjustmentsNewRoute
  '/_authenticated/inventory/adjustments/': typeof AuthenticatedInventoryAdjustmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/privacy'
    | '/support'
    | '/trial'
    | '/dashboard'
    | '/customers/$customerId'
    | '/errors/$error'
    | '/purchase-orders/detail'
    | '/purchase-orders/history'
    | '/sale-orders/detail'
    | '/sale-orders/history'
    | '/settings/account'
    | '/staffs/$staffId'
    | '/supplier-payments/history'
    | '/suppliers/$supplierId'
    | '/bank-accounts/'
    | '/categories/'
    | '/customers/'
    | '/data-migration/'
    | '/inventory/'
    | '/locations/'
    | '/products/'
    | '/purchase-orders/'
    | '/sale-orders/'
    | '/settings/'
    | '/staffs/'
    | '/suppliers/'
    | '/inventory/adjustments/new'
    | '/inventory/adjustments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/privacy'
    | '/support'
    | '/trial'
    | '/dashboard'
    | '/customers/$customerId'
    | '/errors/$error'
    | '/purchase-orders/detail'
    | '/purchase-orders/history'
    | '/sale-orders/detail'
    | '/sale-orders/history'
    | '/settings/account'
    | '/staffs/$staffId'
    | '/supplier-payments/history'
    | '/suppliers/$supplierId'
    | '/bank-accounts'
    | '/categories'
    | '/customers'
    | '/data-migration'
    | '/inventory'
    | '/locations'
    | '/products'
    | '/purchase-orders'
    | '/sale-orders'
    | '/settings'
    | '/staffs'
    | '/suppliers'
    | '/inventory/adjustments/new'
    | '/inventory/adjustments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(landing)/privacy'
    | '/(landing)/support'
    | '/(landing)/trial'
    | '/_authenticated/dashboard'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/purchase-orders/detail'
    | '/_authenticated/purchase-orders/history'
    | '/_authenticated/sale-orders/detail'
    | '/_authenticated/sale-orders/history'
    | '/_authenticated/settings/account'
    | '/_authenticated/staffs/$staffId'
    | '/_authenticated/supplier-payments/history'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/bank-accounts/'
    | '/_authenticated/categories/'
    | '/_authenticated/customers/'
    | '/_authenticated/data-migration/'
    | '/_authenticated/inventory/'
    | '/_authenticated/locations/'
    | '/_authenticated/products/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/sale-orders/'
    | '/_authenticated/settings/'
    | '/_authenticated/staffs/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/inventory/adjustments/new'
    | '/_authenticated/inventory/adjustments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  landingPrivacyRoute: typeof landingPrivacyRoute
  landingSupportRoute: typeof landingSupportRoute
  landingTrialRoute: typeof landingTrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(landing)/trial': {
      id: '/(landing)/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof landingTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/support': {
      id: '/(landing)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof landingSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/privacy': {
      id: '/(landing)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof landingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staffs/': {
      id: '/_authenticated/staffs/'
      path: '/staffs'
      fullPath: '/staffs/'
      preLoaderRoute: typeof AuthenticatedStaffsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sale-orders/': {
      id: '/_authenticated/sale-orders/'
      path: '/sale-orders'
      fullPath: '/sale-orders/'
      preLoaderRoute: typeof AuthenticatedSaleOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-migration/': {
      id: '/_authenticated/data-migration/'
      path: '/data-migration'
      fullPath: '/data-migration/'
      preLoaderRoute: typeof AuthenticatedDataMigrationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-accounts/': {
      id: '/_authenticated/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/bank-accounts/'
      preLoaderRoute: typeof AuthenticatedBankAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier-payments/history': {
      id: '/_authenticated/supplier-payments/history'
      path: '/supplier-payments/history'
      fullPath: '/supplier-payments/history'
      preLoaderRoute: typeof AuthenticatedSupplierPaymentsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staffs/$staffId': {
      id: '/_authenticated/staffs/$staffId'
      path: '/staffs/$staffId'
      fullPath: '/staffs/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffsStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sale-orders/history': {
      id: '/_authenticated/sale-orders/history'
      path: '/sale-orders/history'
      fullPath: '/sale-orders/history'
      preLoaderRoute: typeof AuthenticatedSaleOrdersHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sale-orders/detail': {
      id: '/_authenticated/sale-orders/detail'
      path: '/sale-orders/detail'
      fullPath: '/sale-orders/detail'
      preLoaderRoute: typeof AuthenticatedSaleOrdersDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/history': {
      id: '/_authenticated/purchase-orders/history'
      path: '/purchase-orders/history'
      fullPath: '/purchase-orders/history'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/detail': {
      id: '/_authenticated/purchase-orders/detail'
      path: '/purchase-orders/detail'
      fullPath: '/purchase-orders/detail'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/adjustments/': {
      id: '/_authenticated/inventory/adjustments/'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments/'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/adjustments/new': {
      id: '/_authenticated/inventory/adjustments/new'
      path: '/inventory/adjustments/new'
      fullPath: '/inventory/adjustments/new'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPurchaseOrdersDetailRoute: typeof AuthenticatedPurchaseOrdersDetailRoute
  AuthenticatedPurchaseOrdersHistoryRoute: typeof AuthenticatedPurchaseOrdersHistoryRoute
  AuthenticatedSaleOrdersDetailRoute: typeof AuthenticatedSaleOrdersDetailRoute
  AuthenticatedSaleOrdersHistoryRoute: typeof AuthenticatedSaleOrdersHistoryRoute
  AuthenticatedStaffsStaffIdRoute: typeof AuthenticatedStaffsStaffIdRoute
  AuthenticatedSupplierPaymentsHistoryRoute: typeof AuthenticatedSupplierPaymentsHistoryRoute
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRoute
  AuthenticatedBankAccountsIndexRoute: typeof AuthenticatedBankAccountsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDataMigrationIndexRoute: typeof AuthenticatedDataMigrationIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedSaleOrdersIndexRoute: typeof AuthenticatedSaleOrdersIndexRoute
  AuthenticatedStaffsIndexRoute: typeof AuthenticatedStaffsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedInventoryAdjustmentsNewRoute: typeof AuthenticatedInventoryAdjustmentsNewRoute
  AuthenticatedInventoryAdjustmentsIndexRoute: typeof AuthenticatedInventoryAdjustmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPurchaseOrdersDetailRoute:
    AuthenticatedPurchaseOrdersDetailRoute,
  AuthenticatedPurchaseOrdersHistoryRoute:
    AuthenticatedPurchaseOrdersHistoryRoute,
  AuthenticatedSaleOrdersDetailRoute: AuthenticatedSaleOrdersDetailRoute,
  AuthenticatedSaleOrdersHistoryRoute: AuthenticatedSaleOrdersHistoryRoute,
  AuthenticatedStaffsStaffIdRoute: AuthenticatedStaffsStaffIdRoute,
  AuthenticatedSupplierPaymentsHistoryRoute:
    AuthenticatedSupplierPaymentsHistoryRoute,
  AuthenticatedSuppliersSupplierIdRoute: AuthenticatedSuppliersSupplierIdRoute,
  AuthenticatedBankAccountsIndexRoute: AuthenticatedBankAccountsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDataMigrationIndexRoute: AuthenticatedDataMigrationIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedSaleOrdersIndexRoute: AuthenticatedSaleOrdersIndexRoute,
  AuthenticatedStaffsIndexRoute: AuthenticatedStaffsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedInventoryAdjustmentsNewRoute:
    AuthenticatedInventoryAdjustmentsNewRoute,
  AuthenticatedInventoryAdjustmentsIndexRoute:
    AuthenticatedInventoryAdjustmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  landingPrivacyRoute: landingPrivacyRoute,
  landingSupportRoute: landingSupportRoute,
  landingTrialRoute: landingTrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
